import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import React, { useState, useEffect } from "react";
import { useIsAuthenticated } from "@azure/msal-react";
import { SignInButton } from "../components/SignIn/SignInButton";
import { SignOutButton } from "../components/SignOut/SignOutButton";
import { callMsGraph, callMsGraphTodoTaskList } from "./api/graph";
import { useMsal } from "@azure/msal-react";
import { loginRequest } from "../utils/authConfig";
import styled from "styled-components";
import Todo from "../components/Todo/Todo";
import Schedule from "../components/Schedule/Schedule";

const DataContainer = styled.div`
  margin-top: 1rem;
  display: flex;
  flex-direction: row;

  background: #f2fafc;
  width: 100%;
`;

const Container = styled.div`
  background: white;
  padding: 1rem;
  border: #d9d9d6 1px solid;

  margin: 0.5rem;
  h5 {
    font-weight: 700;
    margin-bottom: 1rem;
  }
`;

export default function Home() {
  const isAuthenticated = useIsAuthenticated();
  const { instance, accounts, inProgress } = useMsal();
  const [accessToken, setAccessToken] = useState(null);
  const [graphData, setGraphData] = useState(null);
  const [taskData, setTaskData] = useState(null);
  const [taskId, setTaskId] = useState("");

  const name = accounts[0] && accounts[0].name;

  const updateTask = (task) => {
    const updatedData = taskData.map((element) => {
      if (element.id === task.id) {
        return { ...element, isExpanded: !element.isExpanded };
      }
      return element;
    });
    setTaskData(updatedData);
  };

  function RequestAccessToken() {
    const request = {
      ...loginRequest,
      account: accounts[0],
    };

    // Silently acquires an access token which is then attached to a request for Microsoft Graph data
    instance
      .acquireTokenSilent(request)
      .then((response) => {
        setAccessToken(response.accessToken);
      })
      .catch((e) => {
        instance.acquireTokenPopup(request).then((response) => {
          setAccessToken(response.accessToken);
        });
      });
  }

  function RequestTodoTaskList(taskId) {
    const request = {
      ...loginRequest,
      account: accounts[0],
    };

    // Silently acquires an access token which is then attached to a request for Microsoft Graph data
    instance
      .acquireTokenSilent(request)
      .then((response) => {
        callMsGraphTodoTaskList(response.accessToken, taskId).then(
          (response) => {
            const updatedData = response.value.map((element) => {
              return { ...element, isExpanded: false };
            });
            setTaskData(updatedData);
          }
        );
      })
      .catch((e) => {
        instance.acquireTokenPopup(request).then((response) => {
          callMsGraph(response.accessToken).then((response) => {
            setGraphData(response);
          });
        });
      });
  }

  function RequestTaskData() {
    const request = {
      ...loginRequest,
      account: accounts[0],
    };

    // Silently acquires an access token which is then attached to a request for Microsoft Graph data
    instance
      .acquireTokenSilent(request)
      .then((response) => {
        callMsGraph(response.accessToken).then((response) => {
          const taskId = response.value[0].id;
          setTaskId(taskId);
          RequestTodoTaskList(taskId);
        });
      })
      .catch((e) => {
        instance.acquireTokenPopup(request).then((response) => {
          callMsGraph(response.accessToken).then((response) => {
            setGraphData(response);
          });
        });
      });
  }

  useEffect(() => {
    if (isAuthenticated) {
      RequestAccessToken();
      RequestTaskData();
    }
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <p>{isAuthenticated ? <SignOutButton /> : <SignInButton />}</p>
        <DataContainer>
          <Container>
            {taskData ? (
              <Todo
                tasks={taskData}
                taskListId={taskId}
                accessToken={accessToken}
                updateTask={updateTask}
              />
            ) : (
              <button onClick={RequestTaskData}>Get Task List</button>
            )}
          </Container>
          <Container>
            <Schedule instance={instance} account={accounts[0]} />
          </Container>
        </DataContainer>
      </main>
    </div>
  );
}
